# Generated by Django 5.2.6 on 2025-09-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='points',
        ),
        migrations.AddField(
            model_name='customuser',
            name='experience_points',
            field=models.IntegerField(default=0, verbose_name='experience_points'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mana_points',
            field=models.PositiveIntegerField(default=0, verbose_name='mana_points'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='rank',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Advanced')], default=0, verbose_name='rank'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='skills',
            field=models.JSONField(default={}, verbose_name='skills'),
        ),
    ]
