# Generated by Django 5.2.6 on 2025-09-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='experience_points',
            field=models.PositiveIntegerField(default=0, verbose_name='experience_points'),
        ),
    ]
