# Generated by Django 5.2.6 on 2025-09-23 08:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_experience_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=0, unique=True, verbose_name='level')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('required_exp', models.PositiveIntegerField(default=0, verbose_name='required exp')),
            ],
            options={
                'ordering': ['required_exp'],
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='experience_points',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mana_points',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='skills',
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='name')),
                ('description', models.CharField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Competence',
                'verbose_name_plural': 'Competences',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='users_compe_name_a95be4_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinLengthValidator(0)])),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.competence')),
            ],
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator], verbose_name='exp')),
                ('mana', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator], verbose_name='mana_points')),
                ('compenteces', models.ManyToManyField(related_name='progress_users', through='users.UserCompetence', to='users.competence', verbose_name='Competences')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.rank', verbose_name='rank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usercompetence',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences_levels', to='users.userprogress'),
        ),
        migrations.AlterUniqueTogether(
            name='usercompetence',
            unique_together={('progress', 'competence')},
        ),
    ]
